services:
  psql:
    container_name: HelCityBikerPsql
    image: postgres:latest
    hostname: psql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    container_name: HelCityBikerApi
    image: node:18-alpine
    build: ./server
    ports:
      - 9001:9001
    depends_on:
     - psql
    environment:
      DB_USER: "postgres"
      DB: "postgres"
      DB_PW:  "postgres"
      DB_PORT: 5432
      DB_HOST: "psql"
      NODE_ENV_POPULATE: "true"
      
volumes:
  postgres-data: